// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lodfuuekcovdmftcevxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvZGZ1dWVrY292ZG1mdGNldnhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MDU2MTEsImV4cCI6MjA2MTQ4MTYxMX0.uJOpVhy6QWRS_N4at31JQhI9Cxr6HYOpP5HRpD8pSac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);